sonar.projectKey=Liquenson_aws-terraform-devops-lab
sonar.projectName=AWS Terraform DevOps Lab
sonar.projectVersion=1.0
sonar.organization=liquensonruben

# Fuentes principales
sonar.sources=docker/src,scripts,kubernetes,helm,argocd,monitoring

# Exclusiones de análisis
sonar.exclusions=**/.terraform/**,**/node_modules/**,**/.git/**,**/environments/**/*.tfvars,**/*.tfstate,**/*.tfstate.backup,**/.terraform.lock.hcl,**/tests/**,**/__pycache__/**

# Exclusiones de cobertura
sonar.coverage.exclusions=**/tests/**,**/__pycache__/**

# Coverage y Python
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11
sonar.terraform.provider.aws.version=5
sonar.scm.provider=git
