sonar.projectKey=liquensonruben_aws-terraform-devops-lab
sonar.projectName=AWS Terraform DevOps Lab
sonar.projectVersion=1.0
sonar.organization=liquensonruben

# Analiza TODO el repo
sonar.sources=.

# Lenguajes relevantes
sonar.inclusions=**/*.tf,**/*.yaml,**/*.yml,**/*.sh,**/*.py

# Excluir ruido
sonar.exclusions=**/.terraform/**,**/node_modules/**,**/.git/**,**/environments/**/*.tfvars,**/*.tfstate,**/*.tfstate.backup,**/.terraform.lock.hcl

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11
sonar.terraform.provider.aws.version=5
sonar.scm.provider=git
sonar.branch.name=main