sonar.projectKey=aws-terraform-devops-lab
sonar.projectName=AWS Terraform DevOps Lab
sonar.projectVersion=1.0

# Analiza TODO el repo
sonar.sources=.

# Lenguajes relevantes en tu proyecto
sonar.inclusions=**/*.tf,**/*.yaml,**/*.yml,**/*.sh,**/*.py

# Opcional (evitar ruido)
sonar.exclusions=**/.terraform/**,**/node_modules/**,**/.git/**
