prometheus:
  prometheusSpec:
    retention: 15d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          resources:
            requests:
              storage: 50Gi
    externalLabels:
      cluster: devops-cluster
      region: eu-west-1

grafana:
  adminPassword: "admin123"
  ingress:
    enabled: true
    hosts:
      - grafana.devops-lab.com
